name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  faker: ^2.1.0
 
  hive: ^2.2.3

  shelf: ^1.4.1
  shelf_router: ^1.1.4


  path: ^1.8.0
  mysql_client: ^0.0.27
  jaguar_jwt: ^3.0.0
  jwt_io: ^1.1.6
  dart_jsonwebtoken: ^2.13.0
  bcrypt: ^1.1.3
  mailer: ^6.1.0
  shelf_cors_headers: ^0.1.5
  graphview: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
