openapi: 3.0.0
info:
  title: Sanglen Yek Salai API
  description: |
    A simple API for Meitei Yek Salai.
    <br>
    <br>
    <img src="https://code.visualstudio.com/assets/images/code-stable.png" width="20" height="20" alt="VS Code icon">
    [Open VS Code](https://github.dev/Santacubeten/server_sanglen) (opens in new tab)
  version: 1.0.0
servers:

  - url: http://10.10.1.38:3000
    description: Server running PC
  - url: http://localhost:3000
    description: Local server
  - url: http://192.168.29.191:3000
    description: Home
tags:
  - name: Clan
    description: Operations about clans
  - name: Surname
    description: Operations about surnames
paths:
  /clans:
    get:
      tags:
        - Clan
      summary: Get all clans
      responses:
        "200":
          description: A list of clans.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Clan"
    post:
      tags:
        - Clan
      summary: Create a new clan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClanInput"
      responses:
        "200":
          description: Clan created successfully.
  /clans/{id}:
    get:
      tags:
        - Clan
      summary: Get a clan by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single clan.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clan"
        "404":
          description: Clan not found.
    put:
      tags:
        - Clan
      summary: Update a clan by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClanInput"
      responses:
        "200":
          description: Clan updated successfully.
    delete:
      tags:
        - Clan
      summary: Delete a clan by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Clan deleted successfully.

  /surnames:
    get:
      tags:
        - Surname
      summary: Get all surnames
      responses:
        "200":
          description: A list of surnames.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Surname"
    post:
      tags:
        - Surname
      summary: Create a new surname
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SurnameInput"
      responses:
        "200":
          description: Surname created successfully.
  /surnames/{id}:
    get:
      tags:
        - Surname
      summary: Get a surname by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single surname.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Surname"
        "404":
          description: Surname not found.
    put:
      tags:
        - Surname
      summary: Update a surname by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SurnameInput"
      responses:
        "200":
          description: Surname updated successfully.
    delete:
      tags:
        - Surname
      summary: Delete a surname by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Surname deleted successfully.
  /surnames/clan/{clanId}:
    get:
      tags:
        - Surname
      summary: Get surnames by Clan ID
      parameters:
        - name: clanId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A list of surnames for the given clan ID.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Surname"
  /yek_details:
    get:
      tags:
        - Yek Details
      summary: Get All Yek Details
      responses:
        "200":
          description: A List of Yek Details.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/yek_Details"

    post:
      tags:
        - Yek Details
      summary: Create a new Yek Detail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/yek_Details"
      responses:
        "200":
          description: Yek Detail created successfully.

  /yek_details/{id}:
    patch:
      tags:
        - Yek Details
      summary: Partially update a Yek Detail
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/yek_Details"
      responses:
        "200":
          description: Yek Detail updated successfully
    get:
      tags:
        - Yek Details
      summary: Get a Yek Detail by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single Yek Detail.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/yek_Details"
        "404":
          description: Yek Detail not found

    delete:
      tags:
        - Yek Details
      summary: Delete a Yek Detail by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Yek Detail deleted successfully

  /yek_details/by_clan_id/{clanId}:
    get:
      tags:
        - Yek Details
      summary: Get Yek Detail by Clan ID
      parameters:
        - name: clanId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A Yek Detail for the given Clan ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/yek_Details"
        "404":
          description: Yek Detail not found for given Clan ID

components:
  schemas:
    yek_Details:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        clan_id:
          type: integer
        firewood:
          type: string
        color:
          type: string
          example: "#ffcc00"
        flower:
          type: string
        fruit:
          type: string
        fish:
          type: string
        sword:
          type: string
        created_at:
          type: string
          format: date-time,
          readOnly: true
    Clan:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        created_by:
          type: string
        surnames:
          type: array
          items:
            $ref: "#/components/schemas/Surname"
    ClanInput:
      type: object
      properties:
        name:
          type: string
        created_by:
          type: string
      required:
        - name
    Surname:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        clan_id:
          type: integer
      required:
        - name
        - clan_id
    SurnameInput:
      type: object
      properties:
        name:
          type: string
        clan_id:
          type: integer
      required:
        - name
        - clan_id
